---
# Création de l'utilisateur worker sur les machines de calcul distribué
- name: Configuration des workers
  hosts: calcul_distribue
  become: true  # Pour avoir les privilèges root
  
  tasks:
    - name: Création de l'utilisateur worker
      ansible.builtin.user:
        name: worker
        state: present
        shell: /bin/bash
        system: false
        create_home: true
        # groups: sudo  # Décommenter si vous voulez ajouter l'utilisateur au groupe sudo
        
    - name: Configuration SSH pour l'utilisateur worker
      ansible.builtin.authorized_key:
        user: worker
        state: present
        key: "{{ lookup('file', '/home/deployer/.ssh/id_ed25519.pub') }}"
        
    # Optionnel : Configuration sudo sans mot de passe
    # - name: Configuration des droits sudo
    #   ansible.builtin.lineinfile:
    #     path: /etc/sudoers.d/worker
    #     line: "worker ALL=(ALL) NOPASSWD:ALL"
    #     create: yes
    #     mode: '0440'
    #     validate: /usr/sbin/visudo -cf %s